FROM registry.wildfireworkspace.com/eop/streamlit-1.0/default-base:latest AS base

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

RUN apt-get update && apt-get install -y gcc ffmpeg libkrb5-dev

# Copy utils over
COPY data_toolbox/utils/skopeutils-0.1.5.tar.gz /datatoolbox/data_toolbox/utils/skopeutils-0.1.5.tar.gz

# Install the python dependencies.
COPY container_requirements.txt /datatoolbox/container_requirements.txt
RUN pip install -r ./container_requirements.txt --timeout=12000
