[tool.ruff]
line-length = 90
lint.select = ["E", "F"]
lint.ignore = [
    "RUF", "ANN", "S101", "D406", "D203", "D213", "T201", 
    "D100", "FBT002", "RET504", "E501", "TC003", "TC001", 
    "FBT001", "C901", "PLR0912", "PLR0915", "D205", "PD901", 
    "PD002", "FIX002", "TD002", "TD003"
]
lint.fixable = ["I"]
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    ".env",
    "static"
]

[tool.ruff.lint.per-file-ignores]
# Ignore test files, just be happy there are tests.
"*test*.py" = ["ALL"]
"_image_triage_helpers.py" = ["E402"] # Need to update logging settings at top of file.
"main.py" = ["E402"] # Ignore rule as config call must come before imports.
"**/{archived_tools}/*" = ["ALL"] # No need to lint deprecated tools.
"**/{tool_template}/*" = ["TD002", "TD003", "FIX002"]
"**/{streamlit_analytics}/*" = ["T201"]
# Tell ruff to be quiet about docstrings and unused imports in inits
"__init__.py" = ["D104", "F401"]
