import random


def get_loading_message():
    """Return a random string that is funny and may or may not be related to technology.

    Returns:
    -------
        str: A random string that is funny and may or may not be related to technology.

    """
    loading_messages = [
    "Reticulating splines...",
    "Generating witty dialog...",
    "Swapping time and space...",
    "Spinning violently around the y-axis...",
    "Tokenizing real life...",
    "Bending the spoon...",
    "Filtering morale...",
    "Don't think of purple hippos...",
    "We need a new fuse...",
    "Have a good day...",
    "The bits are breeding...",
    "(Pay no attention to the man behind the curtain)",
    "...please enjoy the elevator music...",
    "Don't worry - a few bits tried to escape, but we caught them.",
    "Would you like fries with that?",
    "Checking the gravitational constant in your locale...",
    "Go ahead -- hold your breath!",
    "...at least you're not on hold...",
    "Hum something loud while others stare..",
    "The server is powered by a lemon and two electrodes...",
    "We're testing your patience...",
    "Follow the white rabbit...",
    "Why don't you order a sandwich?",
    "Waiting for the satellite to move into position...",
    "The bits are flowing slowly today...",
    "It's still faster than you could do it...",
    "I should have had another RipIT this morning...",
    "My other loading screen is much faster...",
    "(Insert quarter)",
    "Are we there yet?",
    "Have you lost weight?",
    "Just count to 10...",
    "Why so serious?",
    "It's not you. It's me...",
    "Counting backwards from Infinity...",
    "Don't panic...",
    "Embiggening Prototypes",
    "Do not run! We are your friends!",
    "Do you come here often?",
    "Warning: Don't set yourself on fire...",
    "We're making you a cookie...",
    "Creating time-loop inversion field...",
    "Spinning the wheel of fortune...",
    "Loading the enchanted bunny...",
    "Computing chance of success...",
    "I feel like im supposed to be loading something. . .",
    "Should have used a compiled language...",
    "Is this Windows?",
    "Adjusting flux capacitor...",
    "Wait! Don't break your screen yet! It's almost done...",
    "I swear it's almost done...",
    "Let's take a mindfulness minute...",
    "Keeping all the 1's and removing all the 0's...",
    "Putting the icing on the cake. The cake is not a lie...",
    "Cleaning off the cobwebs...",
    "Making sure all the i's have dots...",
    "Granting wishes...",
    "Time flies when you’re having fun...",
    "Get some coffee and come back in ten minutes..",
    "Spinning the hamster...",
    "99 bottles of beer on the wall..",
    "Stay awhile and listen..",
    "Be careful not to step in the git-gui",
    "You shall not pass! yet..",
    "Convincing AI not to turn evil..",
    "Your left thumb points to the right and your right thumb points to the left.",
    "How did you get here?",
    "Wait, do you smell something burning?",
    "Computing the secret to life, the universe, and everything...",
    "Life is Short – Please Wait...",
    "Optimism – is a lack of information.....",
    "Whenever I find the key to success, someone changes the lock...",
    "Sometimes I think war is God’s way of teaching us geography...",
    "I’ve got problem for your solution…..",
    "I think I am, therefore, I am. I think...",
    "Constructing additional pylons...",
    "Roping some seaturtles...",
    "We are not liable for any broken screens as a result of waiting...",
    "Have you tried turning it off and on again?",
    "Well, this is embarrassing...",
    "The Elders of the Internet would never stand for it.",
    "Space is invisible mind dust, and stars are but wishes.",
    "Didn't know paint dried so quickly...",
    "Dividing by zero...",
    "Spawn more Overlord!",
    "If I’m finished in five minutes, just wait longer...",
    "Some days, you just can’t get rid of a bug!",
    "We’re going to need a bigger boat...",
    "Cracking military-grade encryption...",
    "Simulating traveling salesman...",
    "Proving P=NP...",
    "Entangling superstrings...",
    "Twiddling thumbs...",
    "Searching for plot device...",
    "Trying to sort in O(n)...",
    "Laughing at your pictures-i mean, loading...",
    "Sending data to NS-i mean, our servers...",
    "Looking for sense of humour, please hold on...",
    "Please wait while the junior dev refills his coffee...",
    "A different error message? Finally, some progress!",
    "Hold on while we wrap up our git together...sorry",
    "Please hold on as we reheat our coffee...",
    "Kindly hold on as we convert this bug to a feature...",
    "Kindly hold on as our intern quits vim...",
    "Winter is coming...",
    "Installing dependencies...",
    "Don't pet the cats...",
    "Finding someone to hold my beer...",
    "BRB, working on my side project...",
    "@todo Insert witty loading message...",
    "Let's hope it's worth the wait...",
    "Aw, snap! Not..",
    "Ordering 1s and 0s...",
    "Updating dependencies...",
    "Whatever you do, don't look behind you...",
    "Please wait... Consulting the manual...",
    "Loading funny message...",
    "Feel free to spin in your chair...",
    "What's under there?",
    "Your computer has a virus, its name is Windows!",
    "Go ahead, hold your breath and do a plank till loading is complete",
    "Bored of slow loading spinner, buy more RAM!",
    "Help, I'm trapped in a loader!",
    "What is the difference btwn a hippo and a zippo? One is really heavy, the other is a little lighter",  # noqa: E501
    "Mining some bitcoins...",
    "Downloading more RAM...",
    "Updating to Windows Vista...",
    "Deleting System32 folder...",
    "Alt-F4 speeds things up.",
    "Initializing the initializer...",
    "When was the last time you dusted around here?",
    "Optimizing the optimizer...",
    "Last call for the data bus! All aboard!",
    "Never let a computer know you're in a hurry...",
    "A computer will do what you tell it to do, but that may be much different from what you had in mind.",  # noqa: E501
    "Some things man was never meant to know. For everything else, there's CEM Search...",
    "Unix is user-friendly. It's just very selective about who its friends are...",
    "Shovelling coal into the server...",
    "Pushing pixels...",
    "How about this weather, eh?",
    "Building a wall...",
    "Everything in this universe is either a potato or not a potato",
    "The severity of your issue is always lower than you expected.",
    "Updating Updater...",
    "Downloading Downloader...",
    "Debugging Debugger...",
    "Reading Terms and Conditions for you...",
    "Deleting all your hidden porn...",
    "Running with scissors...",
    "Definitely not a virus...",
    "You may call me Steve.",
    "You seem like a nice person...",
    "Work, work...",
    "Patience! This is difficult, you know...",
    "Discovering new ways of making you wait...",
    "Your time is very important to us. Please wait while we ignore you...",
    "Time flies like an arrow; fruit flies like a banana",
    "Two men walked into a bar; the third ducked...",
    "Sooooo... Have you seen my vacation photos yet?",
    "Sorry we are busy catching em' all, we're done soon",
    "TODO: Insert elevator music",
    "Still faster than a Windows update",
    "Composer hack: Waiting for reqs to be fetched is less frustrating if you add -vvv to your command.",  # noqa: E501
    "Please wait while the minions do their work",
    "Grabbing extra minions",
    "Doing the heavy lifting",
    "We're working very hard .... Really",
    "Waking up the minions",
    "You are number 2843684714 in the queue",
    "Please wait while we serve other customers...",
    "Our premium plan is faster",
    "Feeding unicorns...",
    "Rupturing the subspace barrier",
    "Creating an anti-time reaction",
    "Converging tachyon pulses",
    "Bypassing control of the matter-antimatter integrator",
    "Adjusting the dilithium crystal converter assembly",
    "Reversing the shield polarity",
    "Disrupting warp fields with an inverse graviton burst",
    "Up, Up, Down, Down, Left, Right, Left, Right, B, A.",
    "Do you like my loading animation? I made it myself",
    "Whoah, look at it go!",
    "No, I'm awake. I was just resting my eyes...",
    "One mississippi, two mississippi...",
    "Don't panic...",
    "Ensuring Gnomes are still short...",
    "Baking ice cream...",
    ]

    return loading_messages[random.randint(0, len(loading_messages) - 1)]  # noqa: S311

